### PR TITLE
fix(simd): update SIMD opcodes

### PR DESCRIPTION
**Pull request by ngzhian**
See https://github.com/WebAssembly/simd/pull/452 for finalized opcodes
and https://github.com/WebAssembly/simd/issues/467 for some renamings.

### CODE REVIEW

**Comment by ngzhian** [comment]
Where do the .wasm files in `__fixtures__` come from? Some of them need to be updated. I'm still running the tests and updating snapshot, will rebase later.

**Comment by bmeurer** [comment]
> Where do the .wasm files in `__fixtures__` come from? Some of them need to be updated. I'm still running the tests and updating snapshot, will rebase later.

Those are generated by `jest`. You can pass `-u` to `jest` to rebaseline them.

**Comment by yurydelendik** [comment]
fixes #90 

We probably want to disable some wabt tests. wasmparser.rs disables (until tools settle): simd_boolean.wast, simd_lane.wast, simd_i16x8_arith2.wast, simd_f64x2_rounding.wast, simd_f32x4_rounding.wast.

**Comment by ngzhian** [comment]
Updated with some tests disabled.

**Review by yurydelendik — APPROVED** [review]

**Comment by ngzhian** [comment]
It looks like I can't merge this, please help me :) thanks!

**Comment by bmeurer** [comment]
Done, thanks!

**Pull request merged**
