### PR TITLE
fix(threads): add atomic.fence

### PR DESCRIPTION
**Pull request by ngzhian**
atomic.fence was added to the threads proposal in
https://github.com/WebAssembly/threads/pull/141, and supported in wabt
in
https://github.com/WebAssembly/wabt/commit/d041025854ba2b00b3df9f308914c8aba05dcda9#diff-25d902c24283ab8cfbac54dfa101ad31.

### CODE REVIEW

**Comment by ngzhian** [comment]
Not sure how to add tests, I followed the instructions in the README, added a .wasm file to test/ but it didn't seem to run. When I moved it to test/__fixtures__, it ran and failed, and `npm test update` gave me this:

```
$ npm test update

> wasmparser@3.1.0 test /usr/local/google/home/zhin/ssd2/wasmparser
> jest "update"

No tests found, exiting with code 1
Run with `--passWithNoTests` to exit with code 0
In /usr/local/google/home/zhin/ssd2/wasmparser
  41 files checked.
  testMatch: **/__tests__/**/*.[jt]s?(x), **/?(*.)+(spec|test).[tj]s?(x) - 4 matches
  testPathIgnorePatterns: /node_modules/ - 41 matches
  testRegex:  - 0 matches
Pattern: update - 0 matches
npm ERR! Test failed.  See above for more details.
```

**Comment by ngzhian** [comment]
Perfect, thanks for pointing that out, added in ea031b4.

**Comment by yurydelendik** [comment]
> npm test update gave me this:

Created #74 to update instructions. Use `npm test -- --updateSnapshot`

**Comment by ngzhian** [comment]
I ended up having to update wabt to 1.0.15, because that's when the atomic.fence instruction was added to wabt, otherwise it was failing at the compatibility test.
And the update with wabt required me to fix one of the test in WasmDis.test.ts, which had a redefinition of function error.
(btw for the merge I will do a squash so it's one commit for this fix and change, lmk if you want me to do otherwise.)

**Review by bmeurer — APPROVED** [review]

**Comment by bmeurer** [comment]
@ngzhian thanks for fixing here. Can you roll the new `wasmparser` release into Chrome DevTools?

**Pull request merged**
