### PR TITLE
feat: remove type section from disassembly

### PR DESCRIPTION
**Pull request by bmeurer**
The type section can be reconstructed from the implicit type
information in the remainder of the disassembly, and is generally
just cognitive overhead for developers, especially in the browser
DevTools (see https://crbug.com/1092763 for relevant downstream
issue in Chromium DevTools). Relying on the implicit type information
is far more readable for humans and also avoids the need to dump all
the types in the beginning, which take up precious space since both
Chromium and Firefox DevTools limit the number of lines that are
displayed for large Wasm modules.

This includes a fix to `call_indirect` and `return_call_indirect`,
where we had previously refered to the type by name, and now we
use the abbreviated form for printing types as well.

Refs: #56

### CODE REVIEW

**Comment by EricSL** [comment]
LGTM!

**Comment by yurydelendik** [comment]
Code looks good. Though I would recommend to configure this functionality to be switched to old behavior: presence of the types guarantee safer round trip. From UI perspective we can hide types, and it can be hidden by default, but there maybe a need to show them for non-browser tools.

**Comment by bmeurer** [comment]
> Code looks good. Though I would recommend to configure this functionality to be switched to old behavior: presence of the types guarantee safer round trip. From UI perspective we can hide types, and it can be hidden by default, but there maybe a need to show them for non-browser tools.

Done. Added a `skipTypes` option to the `WasmDisassembler`.

**Pull request merged**
